name: flutter_face_attendance
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  camera: ^0.10.5+9
  flutter:
    sdk: flutter
  flutter_animated_progress_bar: ^1.0.5
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
